version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-postgres-container
    volumes:
      - my-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

volumes:
  my-data: